<Project>
  <PropertyGroup>
    <Authors>SEP</Authors>
    <Product>SAMA</Product>
    <Description>Service Availability Monitoring and Alerting</Description>
    <Copyright>Copyright © 2026 SEP</Copyright>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <MinVerVerbosity>minimal</MinVerVerbosity>
    <MinVerSkip Condition="'$(Configuration)' == 'Debug'">true</MinVerSkip>
    <Version Condition="'$(Configuration)' == 'Debug'">0.1.0-dev</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MinVer" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
