# This is the development compose file, so it only defines support services.

services:
  db:
    image: postgres:18-trixie
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_DB: samadb
      POSTGRES_USER: sama
      POSTGRES_PASSWORD: sama-dev-pw
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - 127.0.0.1:5432:5432

  smtp:
    image: rnwood/smtp4dev:v3
    restart: unless-stopped
    environment:
      - ServerOptions__Urls=http://*:80
    ports:
      - 127.0.0.1:6467:80
      - 127.0.0.1:6468:25

volumes:
  pgdata:
