name: CI

defaults:
  run:
    shell: bash

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux_unit_tests:
    name: Unit Tests on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
      - run: dotnet test
